apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::<ACCOUNT_ID>:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::001041420488:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-C0CI2ZBKVSLZ
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2021-12-07T13:45:47Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1338"
  uid: 96b00fdc-0202-4905-90aa-127098d1afa6
